language: R
sudo: false
cache: packages

r:
  - release
  - devel

notifications:
  email: false

r_packages:
  - covr

r_github_packages:
  ModelOriented/ingredients

after_success:
- Rscript -e 'library(covr); codecov()'
