language: R
sudo: false
cache: packages

r:
  - release
  - devel

Remotes: github::ModelOriented/ingredients

notifications:
  email: false

r_packages:
  - covr

after_success:
- Rscript -e 'library(covr); codecov()'
